title: |md

  # Use cases for Climatrix

| {near: top-center}
user: {
    shape: person
    width: 60
  }

user -> download dataset -> from CDS -> specify dataset
user -> download dataset -> from CDS -> specify date

user -> open dataset -> gridded dataset
user -> sample point cloud
user -> reconstruct
user -> prepare train/test splits
user -> evaluate
