title: |md

  # Use cases for Climatrix

| {near: top-center}
user: {
    shape: person
    width: 60
  }

user -> download dataset
download dataset -> from CDS

from CDS -> specify dataset
from CDS -> specify date
user -> open dataset
open dataset -> dense dataset
open dataset -> sparse dataset

dense dataset -> sample
sample -> uniformly
sample -> normally


user -> reconstruct
sparse dataset -> reconstruct
reconstruct -> IDW
reconstruct -> kiring
reconstruct -> INR


user -> sample point cloud
user -> prepare train/test splits
user -> evaluate
